name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@htunsoehsan'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Load .env variables
        run: |
          echo "Loading .env file"
          source .env
        shell: bash

      - name: Show environment variables
        run: |
          echo "API_KEY: $API_KEY"
          echo "DATABASE_URL: $DATABASE_URL"
